config/routes.rb
MyPartnerSite3::Application.routes.draw do
  get "inbox" => "message#index", :as => :inbox
  get "choose_recipients/index"

  resources :groups

  resources :replies do
    member do
      post "reply_message"
    end
    member do
      post "reply_message_admin"
    end
  end

  match 'admin' => 'admins#index', :as => :admin
  match 'user' => 'admins#user', :as => :list_user
  match 'group_list_admin' => 'admins#group_list', :as => :group_list_admin
  match 'my_groups_admin' => 'admins#my_groups', :as => :my_groups_admin
  match 'sent_message_admin' => 'admins#sended_message', :as => :sent_message_admin
  match 'inbox_admin' => 'admins#inbox', :as => :inbox_admin
  match 'edit_user/:id' => 'admins#edit_user', :as => :edit_user
  match 'update_user/:id' => 'admins#update_user', :as => :update_user,:via => :put
  match 'delete_user/:id' => 'admins#delete_user', :as => :delete_user,:via => :delete
  match 'new', :to => "admins#new"
  match "create_user", :to => "admins#create_user"

  get "home/index"
  get "group_list" => "home#group_list", :as => :group_list
  get "my_groups" => "home#my_groups", :as => :my_groups

  get "groups/:id/join" => "groups#join", :as => :join_group

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  devise_scope :user do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end
  post "create_message/", :to => "message#create_message"
  post "create_message_admin/", :to => "admins#create_message"
  get "choose_recipients/:id", :to => "message#choose_recipients", :as => :choose_recipient
  get "choose_recipients_admin/:id", :to => "admins#choose_recipients", :as => :choose_recipient_admin
 
  post "send_email/", :to => "message#send_email"
  get "sent_message/", :to => "message#sended_message"
  get "reply/:message_id", :to => "message#reply"
  get "reply_admin/:message_id", :to => "admins#reply"
  get "attachments/:id/download", :to => "message#download_attachment", :as => :download_attachment

  root :to => 'home#index'

end

app/models/message.rb
class Message < ActiveRecord::Base

  with_options :dependent => :destroy do |message|
    message.has_many :recipients
    message.has_many :attachments
    message.has_many :replies
    message.has_many :message_flags
  end
  
  after_create :insert_flags

  accepts_nested_attributes_for :attachments
  accepts_nested_attributes_for :recipients
  accepts_nested_attributes_for :replies

  scope :my_inbox, lambda {|user_id|
    where(["recipients.user_id = ?", user_id]).includes(:recipients)
  }

  def insert_flags
    self.recipients.each do |recipient|
      MessageFlag.create({message_id: self.id, user_id: recipient.user_id, readed: false})
    end

    self.message_flags.create({user_id: self.user_id, readed: true})
  end
  
  def readed_by(user_id)
    flag = MessageFlag.where("user_id=? AND message_id=?", user_id, self.id).first
    flag.update_attributes({readed: true})
  end

  def unreaded_by(user_id)
    flag = MessageFlag.where("user_id=? AND message_id=?", user_id, self.id).first
    flag.update_attributes({readed: false})
  end

  def readed?(user_id)
    flag = MessageFlag.where("user_id=? AND message_id=?", user_id, self.id).first
    
    flag.readed? ? true : false
  end

  def send_mail_message(user)
    self.recipients.each do |recipient|
      UserMailer.send_message(recipient.user.email, user,self).deliver
    end
  end

end

app/controllers/message_controller.rb
class MessageController < ApplicationController
  before_filter :get_user_id, :only => [:sended_message, :reply]

  def index
    @messages = Message.my_inbox(current_user.id)
    @title = ".:: #{current_user.username} - Inbox ::."
    @header_name = "Inbox - " + current_user.username + " ( " + @messages.count.to_s + " Messages ) "
  end

  def choose_recipients
    if user_signed_in?
      if current_user.is_admin
        redirect_to choose_recipient_admin_path
      end
      @group = Group.find(params[:id])
      @partners = @group.users.uniq
      @message = Message.new
      @title = ".:: #{current_user.username} - Choose Recipients ::."
    else
      session["group_id"] = params[:id]
      redirect_to new_user_session_path
    end
  end

  def create_message
    @message = Message.new(params[:message])
    if @message.save
      @message.send_mail_message(current_user)
      redirect_to sent_message_path
    else
      @group = Group.find(params[:id])
      @partners = @group.partners

      render :action => "choose_recipients"
    end
  end

  def sended_message
    @title = ".:: #{current_user.username} - Sent Message ::."
    @message = Message.where(:user_id => @user_id)
    @header_name = "Sentbox - " + current_user.username + " ( " + @message.count.to_s + " Email Sent ) "
  end

  def reply
    @header_name = "Replying Message"
    @title = ".:: Replying Message ::."
    @message_id = params["message_id"]
    @message = Message.find(@message_id)
    @message.readed_by(current_user.id)
    @recipients = @message.recipients
    @attachment = @message.attachments
  end

  def download_attachment
    @attachment = Attachment.find(params[:id])

    send_file @attachment.attached_file.path
  end

  private
  
  def get_user_id
    unless current_user.id.nil?
      @user_id = current_user.id
    end
  end
end

app/helpers/message_helper.rb
module MessageHelper
end

app/views/message/choose_recipients.html.erb
<div id="choose_recipients">
  <!--        Script by hscripts.com          -->
  <!--        copyright of HIOX INDIA         -->
  <!-- Free javascripts @ http://www.hscripts.com -->
  <script type="text/javascript">
    checked=false;
    function checkedAll (new_message) {
      var aa= document.getElementById('new_message');
      if (checked == false)
      {
        checked = true
      }
      else
      {
        checked = false
      }
      for (var i =0; i < aa.elements.length; i++)
      {
        aa.elements[i].checked = checked;
      }
    }
  </script>
  <!-- Script by hscripts.com -->

  <% @home_class = "current" %>
  <% count = 0  %>
  <%= form_for @message, :url => create_message_path, :html => { :multipart => true } do |f| %>
    <center>
      <table>
        <tr>
          <th>Recipients</th>
          <td>:</td>
          <td>
            <input type='checkbox' name='checkall' class="button-primary" onclick='checkedAll(new_message);'> Select All<br /><br />
            <% @partners.each_with_index do |partner, index| %>
              <%- unless partner.email.eql?(current_user.email) %>
                <% count += 1 %>
                <% name = partner.username.to_s + " ( " + partner.email + " )" %>
                <%= check_box_tag "message[recipients_attributes][#{index}][user_id]", partner.id %> <%= name %>
                <br/>
              <%- end %>
            <% end %> <br />
          </td>
        </tr>
        <tr>
          <th>Attachments</th>
          <td>:</td>
          <td> <%= file_field_tag "message[attachments_attributes][1][attached_file]" %>  </td>
        </tr>
        <tr>
          <th>Subject</th>
          <td>:</td>
          <td><%= f.text_field "subject" %></td>
          <%= f.hidden_field :user_id, :value => current_user.id %>
        </tr>
        <tr>
          <th>Text</th>
          <td>:</td>
          <td><%= f.text_area "text" %></td>
        </tr>
      </table>
      <%= submit_tag "Submit", :class => "button-primary" %>
    <% end %>
</div>

app/views/message/index.html.erb
<div id="inbox">
  <% @inbox_class = "current" %>
  <%= form_tag do %>
    <center />
    <table>
      <tr>
        <th>No</th>
        <th>Subject</th>
        <th>From</th>
        <th>Replies</th>
        <th>Date</th>
        <th>Time</th>
      </tr>
      <% count = 0 %>
      <% @messages.each do |message| %>
        <tr>
          <td><%= count += 1 %></td>
          <td style="<%= message.readed?(current_user.id) ? "" : "font-weight:bold;" %>"><%= link_to "#{message.subject}", "/reply/#{message.id}" %> </td>
          <td><%= User.find(message.user_id).username %></td>
          <td><%= Reply.where(:message_id => message.id).count %></td>
          <td>
            <%
            days = message.created_at.strftime("%d")
            if (11..13).include?(days.to_i.abs % 100)
              "#{days}th"
            else
              case days.to_i.abs % 10
              when 1; date = message.created_at.strftime("%a, #{days}st %b %Y")
              when 2; date = message.created_at.strftime("%a, #{days}nd %b %Y")
              when 3; date = message.created_at.strftime("%a, #{days}rd %b %Y")
              else    date = message.created_at.strftime("%a, #{days}th %b %Y")
              end
            end
          %>
            <%= date %>
          </td>
          <td><%= message.created_at.strftime("%I:%M %p") %></td>
        </tr>
      <% end %>
    </table>
  <% end %>
</div>

app/views/message/reply.html.erb
<div id="reply">
  <center>
    <%=form_tag reply_message_reply_path(@message.id) do%>
      <p style="font-size: 25px;"><b>Message Sender </b> :
        <% if current_user.id == @message.user_id %>
          <%= "You ( #{current_user.username} )" %>
        <% else  %>
          <%= "#{User.find(@message.user_id).username}" %>
        <% end %>
      </p>
      <hr width="50%">
      <table>
        <tr>
          <th>Recipients</th>
          <th>:</th>
          <td>
            <% count = 0 %>
            <% begin %>
              <%  @recipients.each do |recipient| %>
                <% count += 1 %>
                <%= count.to_s + ". " %>
                <%= recipient.user.email %><br />
              <% end %>
            <%rescue%>
            <%end %>
          </td>
        </tr>
        <tr>
          <th>Attachment</th>
          <th>:</th>
          <td>
            <% @attachment.each do |attachment| %>
              <%= link_to attachment.attached_file_file_name, download_attachment_path(attachment), :method => :post %>
            <% end %>
          </td>
        </tr>
        <tr>
          <th>Subject</th>
          <th>:</th>
          <td>
            <%= @message.subject %>
          </td>
        </tr>
        <tr>
          <th>Text</th>
          <th>:</th>
          <td>
            <%= @message.text %>
          </td>
        </tr>
      </table>
      <%-counter = 0%>
      <%@message.replies.each do |reply|%>
        <%counter +=1%>
        <hr width="50%">
        <br />
        <table>
          <caption><font size="3px"><u><b>
                  <%=
                  if (11..13).include?(counter.to_i.abs % 100)
                    "#{counter}th"
                  else
                    case counter.to_i.abs % 10
                    when 1; "#{counter}st"
                    when 2; "#{counter}nd"
                    when 3; "#{counter}rd"
                    else    "#{counter}th"
                    end
                  end
                %> Reply</b></u></font></caption>
          <tr>
            <td colspan="3"><%= reply.created_at.strftime("%a, %d %b %Y") %> on <%= reply.created_at.strftime("%I:%M %p") %></td>
          </tr>
          <tr>
            <td style="text-align: left">Reply From</td>
            <td>:</td>
            <td style="text-align: left"><%= reply.user.username %></td>
          </tr>
          <tr>
            <td style="text-align: left">Text</td>
            <td>:</td>
            <td style="text-align: left"><%=  reply.content %></td>
          </tr>
        </table>
      <%end%>
        <hr width="50%" /> <br />
      <%=  text_area_tag 'content' %><br /><br />
      <%=  submit_tag 'Submit', :class => "button-primary" %>
    <%end%>
  </center>
</div>

app/views/message/send_email.html.erb
<div class="message">
  <h1>Sending Email</h1>
  <hr class="line" />
  <%= form_tag inbox_path do%>
    <center>
      <table class="table_message">
        <tr>
          <th>Recipients</th>
          <td>:</td>
          <td>Recipient</td>
        </tr>
        <tr>
          <th>Attachments</th>
          <td>:</td>
          <td>Attachment</td>
        </tr>
        <tr>
          <th>Subject</th>
          <td>:</td>
          <td><%= text_field_tag "" %></td>
        </tr>
        <tr>
          <th>Text</th>
          <td>:</td>
          <td><%= text_area_tag "" %></td>
        </tr>
      </table>
    </center>
    <%= submit_tag "Submit" %>
  <% end %>
  <hr class="line" />
  <p>Company Name</p>
</div>

app/views/message/sended_message.html.erb
<div id="sent_message">
  <% @sent_message_class = "current" %>
  <%= form_tag do  %>
    <center>
      <table>
        <tr>
          <th style="text-align: left">No</th>
          <th style="text-align: left">Subject</th>
          <th style="text-align: left">Recipients</th>
          <th style="text-align: left">Replies</th>
          <th style="text-align: left">Date</th>
          <th style="text-align: left">Time</th>
        </tr>
        <% count = 0 %>
        <% @message.each do |message| %>
          <% @recipient = message.recipients   %>
          <tr>
            <td><%= count += 1 %></td>
            <td><%= link_to "#{message.subject}", "/reply/#{message.id}" %> </td>
            <td>( <%= @recipient.count %>  person )</td>
            <td><%= Reply.where(:message_id => message.id).count %></td>
            <td>
              <%
              days = message.created_at.strftime("%d")
              if (11..13).include?(days.to_i.abs % 100)
                "#{days}th"
              else
                case days.to_i.abs % 10
                when 1; date = message.created_at.strftime("%a, #{days}st %b %Y")
                when 2; date = message.created_at.strftime("%a, #{days}nd %b %Y")
                when 3; date = message.created_at.strftime("%a, #{days}rd %b %Y")
                else    date = message.created_at.strftime("%a, #{days}th %b %Y")
                end
              end
            %>
              <%= date %>
            </td>
            <td><%= message.created_at.strftime("%I:%M %p") %></td>
          </tr>
        <% end %>
      </table>
    <% end %>
</div>