config/routes.rb
MyPartnerSite3::Application.routes.draw do
  get "inbox" => "message#index", :as => :inbox
  get "choose_recipients/index"

  resources :groups

  resources :replies do
    member do
      post "reply_message"
    end
    member do
      post "reply_message_admin"
    end
  end

  match 'admin' => 'admins#index', :as => :admin
  match 'user' => 'admins#user', :as => :list_user
  match 'group_list_admin' => 'admins#group_list', :as => :group_list_admin
  match 'my_groups_admin' => 'admins#my_groups', :as => :my_groups_admin
  match 'sent_message_admin' => 'admins#sended_message', :as => :sent_message_admin
  match 'inbox_admin' => 'admins#inbox', :as => :inbox_admin
  match 'edit_user/:id' => 'admins#edit_user', :as => :edit_user
  match 'update_user/:id' => 'admins#update_user', :as => :update_user,:via => :put
  match 'delete_user/:id' => 'admins#delete_user', :as => :delete_user,:via => :delete
  match 'new', :to => "admins#new"
  match "create_user", :to => "admins#create_user"

  get "home/index"
  get "group_list" => "home#group_list", :as => :group_list
  get "my_groups" => "home#my_groups", :as => :my_groups

  get "groups/:id/join" => "groups#join", :as => :join_group

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  devise_scope :user do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end
  post "create_message/", :to => "message#create_message"
  post "create_message_admin/", :to => "admins#create_message"
  get "choose_recipients/:id", :to => "message#choose_recipients", :as => :choose_recipient
  get "choose_recipients_admin/:id", :to => "admins#choose_recipients", :as => :choose_recipient_admin
 
  post "send_email/", :to => "message#send_email"
  get "sent_message/", :to => "message#sended_message"
  get "reply/:message_id", :to => "message#reply"
  get "reply_admin/:message_id", :to => "admins#reply"
  get "attachments/:id/download", :to => "message#download_attachment", :as => :download_attachment

  root :to => 'home#index'

end

app/views/layouts/admin.html.erb
<!DOCTYPE HTML>
<html lang="en-US" dir="ltr">
  <head>
    <title><%= @title %></title>
    <link rel='stylesheet' id='colors-fresh-css'  href='https://s-ssl.wordpress.com/wp-admin/css/colors-fresh.css?m=1309726244g&#038;ver=20110703' type='text/css' media='all' />
    <link rel='stylesheet' href='https://s-ssl.wordpress.com/wp-admin/css/wpcom.css?m=1320392177g&#038;version=MU' type='text/css' />
    <script type='text/javascript' src='https://s-ssl.wordpress.com/wp-includes/js/jquery/jquery.js?ver=1.6.1'></script>
    <script type='text/javascript' src='https://s-ssl.wordpress.com/wp-content/themes/h4/js/scripts.js?ver=MU'></script>
    <script type='text/javascript' src='https://s-ssl.wordpress.com/wp-content/themes/h4/tabs/tab.js?ver=20110821'></script>
    <script type='text/javascript'>
      /* <![CDATA[ */
      var wpcom_optimizely = {"customer_support_signup_cta":true};

      /* ]]> */
    </script>
    <script type='text/javascript' src='https://cdn.optimizely.com/js/7144006.js?ver=20111022'></script>

    <script type="text/javascript">
      var _qevents = _qevents || [];
      (function() {var elem = document.createElement('script');elem.src = (document.location.protocol == "https:" ? "https://secure" : "http://edge") + ".quantserve.com/quant.js";elem.async = true;elem.type = "text/javascript";var scpt = document.getElementsByTagName('script')[0];scpt.parentNode.insertBefore(elem, scpt);  })();
      _qevents.push( { qacct:"p-18-mFEk4J448M", labels:"wp.login-page,language.en,type.wpcom" } );
    </script>
  <noscript><div style="display: none;"><img src="//pixel.quantserve.com/pixel/p-18-mFEk4J448M.gif?labels=wp.login-page%2Clanguage.en%2Ctype.wpcom" height="1" width="1" alt="" /></div></noscript>
      <%= stylesheet_link_tag "login" %>
      <%= stylesheet_link_tag "google-like" %>
</head>
<body>
  <% if user_signed_in? %>
    <% if current_user.is_admin %>
      <div id="navwrap">
        <div id="nav" class="floatleft">
          <%= link_to "Home", admin_path(:keyword => ""), :class => @home_class %>
          <%= link_to "Inbox", inbox_admin_path, :class => @inbox_class %>
          <%= link_to "Sent Message", sent_message_admin_path , :class => @sent_message_class %>
          <%= link_to "My Groups", my_groups_admin_path , :class => @my_groups_class %>
          <%= link_to "Group List", group_list_admin_path, :class => @group_list_class  %>
          <%= link_to "Create User", list_user_path, :class => @create_user_class %>
          <%= link_to "Create Group", groups_path, :class => @create_group_class %>
          <%= link_to "Sign out", destroy_user_session_path %>
        </div>
        <div id="nav" class="floatright">
          <%= link_to "Hello, #{current_user.username}", root_path %>
        </div>
        <div class="clear"></div>
      </div>
    <% else %>
      You're not an admin, <strike>fellas!</strike> <%= link_to "Back to Home", root_path %>
    <% end %>
  <% else %>
    <div id="navwrap">
      <div id="nav" class="floatleft">
        <%= link_to "Sign in", new_user_session_path, :class => @sign_in_class %>
        <%= link_to "Sign up", new_user_registration_path, :class => @sign_up_class %>
      </div>
      <div id="nav" class="floatright">
        <%= link_to "My Partner Site 2011", root_path %>
      </div>
      <div class="clear"></div>
    </div>
  <% end %>
  <%= yield %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE HTML>
<html lang="en-US" dir="ltr">
  <head>
    <title><%= @title %></title>
    <link rel='stylesheet' id='colors-fresh-css'  href='https://s-ssl.wordpress.com/wp-admin/css/colors-fresh.css?m=1309726244g&#038;ver=20110703' type='text/css' media='all' />
    <link rel='stylesheet' href='https://s-ssl.wordpress.com/wp-admin/css/wpcom.css?m=1320392177g&#038;version=MU' type='text/css' />
    <script type='text/javascript' src='https://s-ssl.wordpress.com/wp-includes/js/jquery/jquery.js?ver=1.6.1'></script>
    <script type='text/javascript' src='https://s-ssl.wordpress.com/wp-content/themes/h4/js/scripts.js?ver=MU'></script>
    <script type='text/javascript' src='https://s-ssl.wordpress.com/wp-content/themes/h4/tabs/tab.js?ver=20110821'></script>
    <script type='text/javascript'>
      /* <![CDATA[ */
      var wpcom_optimizely = {"customer_support_signup_cta":true};

      /* ]]> */
    </script>
    <script type='text/javascript' src='https://cdn.optimizely.com/js/7144006.js?ver=20111022'></script>

    <script type="text/javascript">
      var _qevents = _qevents || [];
      (function() {var elem = document.createElement('script');elem.src = (document.location.protocol == "https:" ? "https://secure" : "http://edge") + ".quantserve.com/quant.js";elem.async = true;elem.type = "text/javascript";var scpt = document.getElementsByTagName('script')[0];scpt.parentNode.insertBefore(elem, scpt);  })();
      _qevents.push( { qacct:"p-18-mFEk4J448M", labels:"wp.login-page,language.en,type.wpcom" } );
    </script>
  <noscript><div style="display: none;"><img src="//pixel.quantserve.com/pixel/p-18-mFEk4J448M.gif?labels=wp.login-page%2Clanguage.en%2Ctype.wpcom" height="1" width="1" alt="" /></div></noscript>
      <%= stylesheet_link_tag "login" %>
      <%= stylesheet_link_tag "google-like" %>
</head>
<body>
  <% if user_signed_in? %>
    <div id="navwrap">
      <div id="nav" class="floatleft">
        <%= link_to "Home", root_path(:keyword => ""), :class => @home_class %>
        <%= link_to "Inbox", inbox_path, :class => @inbox_class %>
        <%= link_to "Sent Message", sent_message_path , :class => @sent_message_class %>
        <%= link_to "My Groups", my_groups_path , :class => @my_groups_class %>
        <%= link_to "Group List", group_list_path, :class => @group_list_class  %>
        <%= link_to "Sign out", destroy_user_session_path %>
      </div>
      <div id="nav" class="floatright">
        <%= link_to "Hello, #{current_user.username}", root_path %>
      </div>
      <div class="clear"></div>
    </div>
  <% else %>
    <div id="navwrap">
      <div id="nav" class="floatleft">
        <%= link_to "Home", root_path(:keyword => ""), :class => @home_class %>
        <%= link_to "Sign in", new_user_session_path, :class => @sign_in_class %>
        <%= link_to "Sign up", new_user_registration_path, :class => @sign_up_class %>
      </div>
      <div id="nav" class="floatright">
        <%= link_to "My Partner Site 2011", root_path %>
      </div>
      <div class="clear"></div>
    </div>
  <% end %>
  <%= yield %>
</body>
</html>